const express = require('express');
const router = express.Router();
const Complaint = require('../models/Complaint');
const PDFDocument = require('pdfkit');
const { Parser } = require('json2csv');
const { authenticate, authorize } = require('../middleware/auth');
const AuditLog = require('../models/AuditLog');

// Generate PDF for a single complaint (auth required)
router.get('/pdf/:trackingId', authenticate, async (req, res) => {
  try {
    const complaint = await Complaint.findOne({ trackingId: req.params.trackingId });
    if (!complaint) {
      return res.status(404).json({ error: 'Complaint not found' });
    }

    const doc = new PDFDocument({ margin: 50 });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=complaint-${complaint.trackingId}.pdf`);
    doc.pipe(res);

    // Header
    doc.fontSize(22).font('Helvetica-Bold').text('LekhSahayak', { align: 'center' });
    doc.fontSize(10).font('Helvetica').text('AI-Powered Civic Complaint System', { align: 'center' });
    doc.moveDown();
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke('#0ea5e9');
    doc.moveDown();

    // Complaint details
    doc.fontSize(16).font('Helvetica-Bold').text('Complaint Report');
    doc.moveDown(0.5);

    const details = [
      ['Tracking ID', complaint.trackingId],
      ['Status', complaint.status],
      ['Priority', complaint.priority],
      ['Problem Type', complaint.problemType],
      ['Department', complaint.department],
      ['Location', complaint.location],
      ['Filed On', new Date(complaint.createdAt).toLocaleString()],
      ['SLA Deadline', complaint.slaDeadline ? new Date(complaint.slaDeadline).toLocaleString() : 'N/A'],
    ];

    details.forEach(([label, value]) => {
      doc.fontSize(10).font('Helvetica-Bold').text(`${label}: `, { continued: true });
      doc.font('Helvetica').text(value);
    });

    doc.moveDown();
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke('#e2e8f0');
    doc.moveDown();

    // Raw input
    doc.fontSize(12).font('Helvetica-Bold').text('Original Complaint (Raw Input)');
    doc.moveDown(0.3);
    doc.fontSize(10).font('Helvetica').text(complaint.rawInput, { indent: 20 });
    doc.moveDown();

    // Formal text
    doc.fontSize(12).font('Helvetica-Bold').text('Formal Complaint Draft');
    doc.moveDown(0.3);
    doc.fontSize(10).font('Helvetica').text(complaint.formalText, { indent: 20 });
    doc.moveDown();

    // Timeline
    if (complaint.timeline && complaint.timeline.length > 0) {
      doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke('#e2e8f0');
      doc.moveDown();
      doc.fontSize(12).font('Helvetica-Bold').text('Status Timeline');
      doc.moveDown(0.3);
      complaint.timeline.forEach((event, i) => {
        doc.fontSize(9).font('Helvetica-Bold').text(
          `${i + 1}. [${event.status}] — ${new Date(event.timestamp).toLocaleString()}`
        );
        if (event.note) {
          doc.fontSize(9).font('Helvetica').text(`   ${event.note}`);
        }
        doc.moveDown(0.2);
      });
    }

    // Feedback
    if (complaint.feedback && complaint.feedback.rating) {
      doc.moveDown();
      doc.fontSize(12).font('Helvetica-Bold').text('Citizen Feedback');
      doc.fontSize(10).font('Helvetica').text(`Rating: ${'★'.repeat(complaint.feedback.rating)}${'☆'.repeat(5 - complaint.feedback.rating)}`);
      if (complaint.feedback.comment) {
        doc.text(`Comment: ${complaint.feedback.comment}`);
      }
    }

    // Footer
    doc.moveDown(2);
    doc.fontSize(8).font('Helvetica').fillColor('#94a3b8')
      .text(`Generated by LekhSahayak on ${new Date().toLocaleString()}`, { align: 'center' });

    doc.end();

    // Audit
    await AuditLog.create({
      action: 'export_generated',
      targetType: 'complaint',
      targetId: complaint.trackingId,
      details: `PDF report generated for ${complaint.trackingId}`,
    });

  } catch (error) {
    console.error('PDF generation error:', error);
    res.status(500).json({ error: 'Failed to generate PDF' });
  }
});

// Export all complaints as CSV
router.get('/csv', authenticate, authorize('officer', 'department_head', 'super_admin'), async (req, res) => {
  try {
    const { department, status, priority } = req.query;
    const query = {};
    if (department) query.department = department;
    if (status) query.status = status;
    if (priority) query.priority = priority;

    const complaints = await Complaint.find(query)
      .sort({ createdAt: -1 })
      .lean();

    const fields = [
      'trackingId', 'problemType', 'department', 'priority', 'status',
      'location', 'rawInput', 'formalText', 'createdAt', 'updatedAt',
      'slaDeadline',
    ];

    const parser = new Parser({ fields });
    const csv = parser.parse(complaints);

    res.setHeader('Content-Type', 'text/csv');
    res.setHeader('Content-Disposition', `attachment; filename=complaints-export-${Date.now()}.csv`);
    res.send(csv);

    await AuditLog.create({
      action: 'export_generated',
      actor: req.user._id,
      actorName: req.user.name,
      targetType: 'system',
      details: `CSV export generated (${complaints.length} complaints)`,
    });
  } catch (error) {
    console.error('CSV export error:', error);
    res.status(500).json({ error: 'Failed to generate CSV' });
  }
});

// Monthly summary
router.get('/summary', async (req, res) => {
  try {
    const thirtyDaysAgo = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000);
    const total = await Complaint.countDocuments({ createdAt: { $gte: thirtyDaysAgo } });
    const resolved = await Complaint.countDocuments({
      createdAt: { $gte: thirtyDaysAgo },
      status: 'Resolved',
    });
    const critical = await Complaint.countDocuments({
      createdAt: { $gte: thirtyDaysAgo },
      priority: 'Critical',
    });

    const topDepartments = await Complaint.aggregate([
      { $match: { createdAt: { $gte: thirtyDaysAgo } } },
      { $group: { _id: '$department', count: { $sum: 1 } } },
      { $sort: { count: -1 } },
      { $limit: 5 },
    ]);

    res.json({
      period: '30 days',
      total,
      resolved,
      critical,
      resolutionRate: total > 0 ? Math.round((resolved / total) * 100) : 0,
      topDepartments,
    });
  } catch (error) {
    res.status(500).json({ error: 'Failed to generate summary' });
  }
});

module.exports = router;
